{% set name = "kvh" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kvh-{{ version }}.tar.gz
  sha256: 7f8d9b7c5c4b3abc7784cbb9e6367479dd9cdaea8a1b378dbbf23f337ee89998

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - pip
    - meson
    - meson-python
    - ninja
  run:
    - python

test:
  imports:
    - kvh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://forgemia.inra.fr/mathscell/kvh
  summary: KVH format reader/writer
  dev_url: https://forgemia.inra.fr/mathscell/kvh
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgsokol
